### PR TITLE
added parseWekaOutput.js

### PR DESCRIPTION
**Pull request by dan736923**
- converts Weka output to JSON files

### CODE REVIEW

**Comment by AlexMoroz** [comment]
Build failed

**Comment by AlexMoroz** [comment]
@dan736923  you need to fix it=)

**Comment by sacdallago** [comment]
Com'on @dan736923 this is here since > 20h. Either fix, close or comment.

**Comment by dan736923** [comment]
Only added parseWekaOutput.js, which doesn't generate any errors/warnings. Grunt complains about errors in old version of createARFF.js, which has been fixed in a later commit. Should be fine after merge.

**Comment by sacdallago** [comment]
So first merge develop into this branch, commit, push, and if it works you have a non-breaking pull request

**Pull request merged**
