### PR TITLE
number of predictions is compared with total number of characters

### PR DESCRIPTION
**Pull request by AlexMoroz**

### CODE REVIEW

**Comment by sacdallago** [comment]
Alex opened, alex tested and alex merged? Amazing Alex! :D buuuuttt.. what about having someone else review your PRs? :dancer:

**Comment by AlexMoroz** [comment]
It was here for one day, nobody merged it :confused:

**Comment by AlexMoroz** [comment]
Nobody wants to merge tests :worried:

**Comment by sacdallago** [comment]
:D :D :D ok

**Pull request merged**
